spring:
  application:
    name: timeDeal
  config:
    import: aws-secretsmanager:hotstock/api/keys

  datasource:
    driver-class-name: org.postgresql.Driver
    username: timo
    password: timo
    url: jdbc:postgresql://localhost:5432/stock_service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.hibernate.SQL: info
    org.springframework.web: error
    com.bjcareer.stockservice.timeDeal: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs

redis:
  address: redis://${REDIS_PUBLIC_ADDRESS}:${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  database: ${REDIS_DATABASE}

server:
  tomcat:
    mbeanregistry:
      enabled: true

auth:
  url: http://3.34.191.223:8080

