spring:
  application:
    name: timeDeal
  config:
    import: aws-secretsmanager:hotstock/api/keys

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://${RDB_PRIVATE_ADDRESS}:${RDB_PORT}/time_deal_service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

logging:
  level:
    org.hibernate.SQL: info
    org.springframework.web: error
    com.bjcareer.stockservice.timeDeal: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs

redis:
  address: redis://${REDIS_PRIVATE_ADDRESS}:${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  database: ${REDIS_DATABASE}

server:
  tomcat:
    mbeanregistry:
      enabled: true

auth:
  url: http://${AUTH_SERVER_ADDRESS}:8080
