spring:
  application:
    name: timeDeal

  datasource:
    url: jdbc:postgresql://223.130.142.94:5432/stock_service
    username: timo
    password: timo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web: error
    com.bjcareer.stockservice.timeDeal: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs

redis:
  address:
    master: "redis://223.130.142.94:6379"
    slave:  "redis://223.130.142.94:6479"
  password: "changeme"
  database: 0

server:
  tomcat:
    mbeanregistry:
      enabled: true
