spring:
  application:
    name: timeDeal

  datasource:
    driver-class-name: org.postgresql.Driver
    username: timo
    password: timo
    url: jdbc:postgresql://localhost:5432/stock_service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    org.hibernate.SQL: info
    org.springframework.web: error
    com.bjcareer.stockservice.timeDeal: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs

redis:
  address: redis://localhost:6379
  password: changeme
  database: 0

server:
  tomcat:
    mbeanregistry:
      enabled: true

auth:
  url: http://3.34.191.223:8080
