spring:
  application:
    name: timeDeal

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

logging:
  level:
    org.hibernate.SQL: info
    org.springframework.web: error
    com.bjcareer.stockservice.timeDeal: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs

redis:
  address: ${REDIS_ADDRESS}
  password: ${REDIS_PASSWORD}
  database: ${REDIS_DATABASE}

server:
  tomcat:
    mbeanregistry:
      enabled: true

auth:
  url: ${AUTH_URL}
