version: '3.9'

services:
  gateway:
    container_name: gateway-service
    image: bjwancareer/gateway:latest
    network_mode: host
    restart: always
    env_file:
      - .env
    volumes:
      - service_data:/app
    logging:
      driver: "json-file"
      options:
        max-size: "100m"    # 로그 파일의 최대 크기 설정 (예: 10MB)
        max-file: "3"      # 로그 파일을 회전할 때 보관할 파일 수 (예: 3개 파일 보관)
