{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://3.34.191.223:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/api/v0/user/refresh": {
      "post": {
        "tags": [
          "user-controller"
        ],
        "operationId": "refreshLogin",
        "parameters": [
          {
            "name": "sessionId",
            "in": "cookie",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "refreshToken",
            "in": "cookie",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v0/user/login": {
      "post": {
        "tags": [
          "user-controller"
        ],
        "operationId": "Login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequestDTO"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v0/register": {
      "post": {
        "tags": [
          "register-controller"
        ],
        "summary": "회원가입",
        "description": "사용자가 입력한 이메일 및 패스워드로 회원가입을 진행합니다.",
        "operationId": "register",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterRequestDTO"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/RegisterResponseDTO"
                }
              }
            }
          }
        }
      }
    },
    "/api/v0/register/verify-token": {
      "post": {
        "tags": [
          "register-controller"
        ],
        "summary": "이메일 인증 토큰 검증",
        "description": "사용자가 입력한 이메일로 발송된 토큰을 검증합니다.",
        "operationId": "verifyEmailToken",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MobileAuthenticationVerifyRequestDTO"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/MobileAuthenticationVerifyResponseDTO"
                }
              }
            }
          }
        }
      }
    },
    "/api/v0/register/verify-email": {
      "post": {
        "tags": [
          "register-controller"
        ],
        "summary": "이메일 인증 토큰 생성",
        "description": "사용자가 입력한 이메일로 회원가입 인증을 위한 랜덤 토큰을 생성하고 전송합니다. 중복된 이메일이 있으면 에러를 반환합니다.",
        "operationId": "generateTokenForRegister",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/VerifyEmailRequestDTO"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "LoginRequestDTO": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "RegisterRequestDTO": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "RegisterResponseDTO": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          }
        }
      },
      "MobileAuthenticationVerifyRequestDTO": {
        "type": "object",
        "properties": {
          "token": {
            "type": "integer",
            "format": "int64"
          },
          "email": {
            "type": "string"
          }
        }
      },
      "MobileAuthenticationVerifyResponseDTO": {
        "type": "object",
        "properties": {
          "result": {
            "type": "boolean"
          }
        }
      },
      "VerifyEmailRequestDTO": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          }
        }
      }
    }
  }
}
