spring:
  application:
    name: gateway

auth:
  url: http://3.34.191.223:8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


secret:
    key: 3ac4218e586878871ab0e9febefe81d83740ece704704af22d6a69db940fefc0
logging:
  level:
    com.bjcareer.gateway.*: debug
