spring:
  application:
    name: gateway

redis:
  address: ${REDIS_ADDRESS}
  password: ${REDIS_PASSWORD}
  database: ${REDIS_DATABASE}

secret:
    key: ${SECRET_KEY}

bucket:
  token:
    max-limit: ${MAX_API_LIMIT}
    refill-minute: ${REFILL_API_MINUTE}

auth:
  url: ${AUTH_URL}

search:
  url: ${SEARCH_URL}

logging:
  level:
    com.bjcareer.gateway.*: error

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
