spring:
  application:
    name: gateway
  config:
    import: aws-secretsmanager:hotstock/api/keys

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_PUBLIC_ADDRESS}:27017

redis:
  address: redis://${REDIS_PUBLIC_ADDRESS}:${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  database: ${REDIS_DATABASE}

secret:
  key: ${JWT_SECRET_KEY}

bucket:
  token:
    max-limit: ${MAX_API_LIMIT}
    refill-minute: ${REFILL_API_MINUTE}

auth:
  url: ${AUTH_PUBLIC_SERVER_ADDRESS}

search:
  url: ${SEARCH_PUBLIC_SERVER_ADDRESS}

time-deal:
  url: ${TIMEDEAL_PUBLIC_SERVER_ADDRESS}

logging:
  level:
    com.bjcareer.gateway.*: debug
    org.springframework.cloud.aws: DEBUG


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
