spring:
  application:
    name: gateway
  config:
    import: aws-secretsmanager:hotstock/api/keys

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_PUBLIC_ADDRESS}

redis:
  address: redis://${REDIS_PRIVATE_ADDRESS}:${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  database: ${REDIS_DATABASE}

secret:
  key: ${JWT_SECRET_KEY}

bucket:
  token:
    max-limit: ${MAX_API_LIMIT}
    refill-minute: ${REFILL_API_MINUTE}


auth:
  url: ${AUTH_PRIVATE_SERVER_ADDRESS}


search:
  url: ${SEARCH_PRIVATE_SERVER_ADDRESS}

time-deal:
  url: ${TIMEDEAL_PRIVATE_SERVER_ADDRESS}

logging:
  level:
    com.bjcareer.gateway.*: info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
