spring:
  application:
    name: userservice

  datasource:
    username: timo
    password: timo
    url: jdbc:postgresql://localhost:5432/user_service # 환경변수 사용
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


secret:
  key: 3ac4218e586878871ab0e9febefe81d83740ece704704af22d6a69db940fefc0

redis:
  address: ${REDIS_ADDRESS:redis://localhost:6379}
  password: ${REDIS_PASSWORD:changeme}
  database: ${REDIS_DATABASE:0}

logging:
  level:
    org.hibernate.SQL: debug
    com.bjcareer.userservice: debug   # Set the log level for your specific package

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all endpoints
