spring:
  application:
    name: userservice

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://${RDB_PRIVATE_ADDRESS}:${RDB_PORT}/user_service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_EMAIL_USERNAME}
    password: ${GMAIL_EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

secret:
  key: ${JWT_SECRET_KEY}

redis:
  address: redis://${REDIS_PRIVATE_ADDRESS}:${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  database: ${REDIS_DATABASE}

logging:
  level:
    com.bjcareer.userservice: debug

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: prometheus  # Prometheus 메트릭 엔드포인트만 개방
