version: '3.9'

services:
  user-service:
    container_name: user-service
    image: bjwancareer/userservice:latest
    network_mode: host
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"    # 로그 파일의 최대 크기 설정 (예: 10MB)
        max-file: "3"      # 로그 파일을 회전할 때 보관할 파일 수 (예: 3개 파일 보관)
