spring:
  application:
    name: search

  datasource:
    driver-class-name: org.postgresql.Driver
    username: timo
    password: timo
    url: jdbc:postgresql://localhost:5432/search_service


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

redis:
  address: redis://localhost:6379,redis://localhost:6381
  password: changeme
  database: 0

mongodb:
  database: keywords
  uri: mongodb://changeme:changeme@localhost:27017,mongodb://changeme:changeme@localhost:27018


logging:
  level:
    com.bjcareer.search : debug

# 추가된 설정 항목
database:
  number: ${DATABASE_NUMBER:2}