spring:
  application:
    name: search
  config:
    import: aws-secretsmanager:hotstock/api/keys

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://${RDB_PRIVATE_ADDRESS}:${RDB_PORT}/search_service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        insert_ordering: true
        jdbc:
          batch_size: 50
    show-sql: true


  kafka:
    bootstrap-servers: ${KAFKA_PUBLIC_ADDRESS}:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring.json.trusted.packages: "*"
      auto-offset-reset: earliest
    listener:
      ack-mode: manual
    template:
      default-topic: dead-letter-topic

aws:
  s3:
    bucket: ${BUCKET}
    region: ap-northeast-2
    access-key: ${BUCKET_ACCESS_KEY}
    secret-key: ${BUCKET_SECRET_KEY}


redis:
  address: redis://${REDIS_PUBLIC_ADDRESS}:${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  database: ${REDIS_DATABASE}

mongodb:
  database: keywords
  uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_PUBLIC_ADDRESS}:${MONGO_PORT}

logging:
  level:
    org.hibernate.SQL: debug # SQL 쿼리 로그 출력
    org.hibernate.orm.jdbc.bind: TRACE
    com.bjcareer.search.*: debug

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

naver:
  keyword-custom-id: ${NAVER_KEYWORD_CUSTOM_ID}
  keyword-access-key: ${NAVER_KEYWORD_ACCESSKEY_KEY}
  keyword-secret-key: ${NAVER_KEYWORD_SECRET_KEY}

  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

  client-new-id: ${NAVER_NEWS_CLIENT_ID}
  client-new-secret: ${NAVER_NEWS_CLIENT_SECRET}
GPT:
  api-key: ${GPT_API_KEY}

python-search:
  address: http://${PYTHON_PUBLIC_SEARCH_SERVER_ADDRESS}:${PYTHON_SEARCH_SERVER_PORT}

analyze-search:
  address: http://${ANALYZE_PUBLIC_SERVER_ADDRESS}:8080

