spring:
  application:
    name: search

  datasource:
    driver-class-name: org.postgresql.Driver
    username: timo
    password: timo
    url: jdbc:postgresql://localhost:5432/search_service

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        use_sql_comments: true
    show-sql: true

redis:
  address: redis://localhost:6379
  password: changeme
  database: 0

mongodb:
  database: keywords
  uri: mongodb://changeme:changeme@localhost:27017

logging:
  level:
#    org.hibernate.SQL: debug # SQL 쿼리 로그 출력
    org.hibernate.orm.jdbc.bind: TRACE

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true


database:
  number: 1
  shardingKey: id