spring:
  application:
    name: search

  datasource:
    driver-class-name: org.postgresql.Driver
    username: timo
    password: timo
    url: jdbc:postgresql://localhost:5432/search_service

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    
redis:
  address: redis://localhost:6379
  password: changeme
  database: 0

mongodb:
  database: keywords
  uri: mongodb://changeme:changeme@localhost:27017

logging:
  level:
    org.hibernate.SQL: debug # SQL 쿼리 로그 출력
    org.hibernate.orm.jdbc.bind: TRACE

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
