spring:
  application:
    name: search
  config:
    import:
      aws-secretmanager:
        name: /hotstock/api/keys
        enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_USERNAME}
    url: jdbc:postgresql://${RDB_PUBLIC_ADDRESS}:${RDB_PORT}/search_service

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


redis:
  address: redis://${REDIS_PUBLIC_ADDRESS}:${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  database: ${REDIS_DATABASE}

mongodb:
  database: keywords
  uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_PUBLIC_ADDRESS}:${MONGO_PORT}

logging:
  level:
    org.hibernate.SQL: debug # SQL 쿼리 로그 출력
    org.hibernate.orm.jdbc.bind: TRACE

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

naver:
  keyword-custom-id: ${NAVER_KEYWORD_CUSTOM_ID}
  keyword-access-key: ${NAVER_KEYWORD_ACCESSKEY_KEY}
  keyword-secret-key: ${NAVER_KEYWORD_SECRET_KEY}

  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

  client-new-id: ${NAVER_NEWS_CLIENT_ID}
  client-new-secret: ${NAVER_NEWS_CLIENT_SECRET}
GPT:
  api-key: ${GPT_API_KEY}
